name: Process Gaming Stats

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  process-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Python
      uses: actions/sup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-vision pillow requests

    - name: Run processing script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python game_tracker_v2.py  # Make sure this matches your actual filename

    - name: Upload results
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: gaming-stats-results
        path: images/
